[project]
name = "autodict2anki"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "jinja2>=3.1.6",
    "playwright>=1.48.0",
    "python-dotenv>=1.0.1",
    "requests>=2.32.4",
    "schedule>=1.2.2",
    "selenium>=4.27.1",
    "webdriver-manager>=4.0.2",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
